apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  restartPolicy: OnFailure
  schedulerName: volcano
  containers:
  - image: nvcr.io/nvidia/pytorch:20.06-py3
    name: pod1-ctr
    command: ["sleep"]
    args: ["100000"]
    resources:
      limits:
        volcano.sh/gpu-memory: 1024  # 1024MB
