FROM pytorch/pytorch:1.5.1-cuda10.1-cudnn7-devel as build
ADD cuda-wrapper-prod-volcano.c /cuda-wrapper-prod-volcano.c
RUN gcc -I /usr/local/cuda/include/ /cuda-wrapper-prod-volcano.c -fPIC -shared -ldl -lcuda -o /libcuda.so 

FROM pytorch/pytorch:1.5.1-cuda10.1-cudnn7-runtime
RUN mkdir -p /usr/local/cuda/targets/x86_64-linux/lib/
COPY --from=build /libcuda.so /usr/local/cuda/targets/x86_64-linux/lib/libcuda.10.1.so
COPY --from=build /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.10.1.243 /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so
ENV LD_PRELOAD=/usr/local/cuda/targets/x86_64-linux/lib/libcuda.10.1.so
ENV VOLCANO_GPU_ALLOCATED=1024
